### ISSUE TITLE
Adapting to another Moodle website

### ISSUE THREAD

**Issue by ghost** [gcmalloc/epfl-moodle#9]
Hello,

Will I be able to adapt this to my own school's Moodle?

**Comment by gcmalloc** [comment]
There is some hardcoded url that would need a bit of love.
The login system for EPFL is a bit strange. 

If you factor out those two factor, and have a similar version of moodle for html tags, I see no reason why it wouldn't work.

**Comment by ghost** [comment]
I couldn't figure out the tequila thing :D.

Can you please give me pointers on what to modify in the login function? I went to the login page in my school's Moodle and I can see that the form does a simple post to the page itself (`/login/index.php`).

**Comment by antoinealb** [comment]
Tequila is the name of EPFL's centralized authentication system.

Basically if you want to adapt the login code to your school, you would need to change [the relevant lines](https://github.com/gcmalloc/epfl-moodle/blob/569834e5518bd67345245f500ce974f465831c63/epfl_moodle/moodle.py#L58-L76) to do something like:

```python
payload = {'myUserField': 'yassinei', 'myPasswordField': '424242'}
resp = self.session.post("http://moodle.my-awesome-school.edu/login/index.php", data=payload)
assert resp.status_code == 200
```

You should also change `MAIN_PAGE` to adapt it for your school

**Comment by ghost** [comment]
Great I'll try that.

PS: can't beat the awesomeness http://ensao.ump.ma

**Comment by ghost** [comment]
That DID work :) :)

Thank you very much everyone. Feel free to close the issue.

**Comment by antoinealb** [comment]
Awesome 👍
